- hosts: servers
  user: vagrant
  become: yes
  become_user: root

  tasks:
    # yum repository setting
    - block:
      - name: add yum additional repos
        yum: name=epel-release

      - name: switch enable additional yum repos 
        replace: dest=/etc/yum.repos.d/epel.repo regexp="enabled *= *1" replace="enable=0"

    # install nodejs
    - block:
      - name: prepare nodejs v4.x
        shell: curl --silent --location https://rpm.nodesource.com/setup_4.x | sudo bash -

      - name: install nodejs
        yum: name=nodejs state=present

      - name: add nodejs user
        user: name=nodejs comment="for nodejs executor" group=dialout

