- hosts: servers
  user: vagrant
  become: yes
  become_user: root

  tasks:
    # install curl
    - name: install curl
      apt: name=curl state=present update_cache=yes

    # install nodejs
    - block:
      - name: prepare nodejs v4.x
        shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

      - name: install nodejs
        apt: name=nodejs state=present

      - name: add nodejs user
        user: name=nodejs comment="for nodejs executor" group=dialout

